services:
  frontend-dev:
    build:
      context: bloglist-frontend
      dockerfile: dev.Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=http://localhost/api
      - REACT_APP_ENV=development
    ports:
      - "3000:3000"
    networks:
      - my_network
    volumes:
      - ./bloglist-frontend:/usr/src/app/


  backend-dev:
    build:
      context: bloglist-backend
      dockerfile: dev.Dockerfile
    ports:
      - ":8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - REQUEST_ORIGIN=http://proxy
      - SECRET=Secret
      - DATABASE_URL=mongodb+srv://fullstack:Vv3oxVAaSX5qlGv3@cluster0.ph36nzi.mongodb.net/test?retryWrites=true&w=majority
    networks:
      - my_network
    volumes:
      - ./bloglist-backend:/usr/src/app/


  proxy:
    image: nginx
    hostname: proxy
    container_name: proxy
    tty: true
    stdin_open: true
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge